export const navData = [
  {
    title: "사진",
    english: "Photos",
    path: "",
    isActive: true,
  },
  {
    title: "일러스트",
    english: "illustraitons",
    path: "illustrations",
    isActive: false,
  },
  {
    title: "배경화면",
    english: "Wallpapers",
    path: "",
    isActive: false,
  },
  {
    title: "자연",
    english: "Nature",
    path: "nature",
    isActive: false,
  },
  {
    title: "3D 렌더링",
    english: "3D Renders",
    path: "3d-renders",
    isActive: false,
  },
  {
    title: "텍스처",
    english: "Textures",
    path: "textures-patterns",
    isActive: false,
  },
  {
    title: "건축 및 인테리어",
    english: "Atchitecture & Interiors",
    path: "architecture-interior",
    isActive: false,
  },
  {
    title: "여행하다",
    english: "Travel",
    path: "travel",
    isActive: false,
  },
  {
    title: "필름",
    english: "Film",
    path: "film",
    isActive: false,
  },
  {
    title: "거리사진",
    english: "Street Photography",
    path: "street-photography",
    isActive: false,
  },
  {
    title: "사람",
    english: "Peoples",
    path: "people",
    isActive: false,
  },
  {
    title: "동물",
    english: "Animals",
    path: "animals",
    isActive: false,
  },
  {
    title: "실험적인",
    english: "Experimental",
    path: "experimental",
    isActive: false,
  },
  {
    title: "패션 & 뷰티",
    english: "Fashion & Beauty",
    path: "fashion-beauty",
    isActive: false,
  },
  {
    title: "식음료",
    english: "Food & Drink",
    path: "food-drink",
    isActive: false,
  },
  {
    title: "스포츠",
    english: "Sports",
    path: "sports",
    isActive: false,
  },
  {
    title: "건강 및 웰빙",
    english: "Health & Wellness",
    path: "health",
    isActive: false,
  },
];
